routes/web.php
Route::post('/uniqueemail', "UserController@uniqueemail");
Route::post('/uniqueuser_edit', "UserController@uniqueuser_edit");
Route::post('/uniqueemail_edit', "UserController@uniqueemail_edit");

/* Social Login facebook,google,twitter */
// Route::get('/redirect/{provider}', 'SocialAuthController@redirect');
// Route::get('/callback/{provider}', 'SocialAuthController@callback');


// Route::get('home', array('as' => 'home', 'uses' => function(){
  // return view('home');
// }));


/* Language */
Route::get('/language', "LanguageController@index");
Route::post('LanguageController/store', ['as' => 'languages.store', 'uses' => 'LanguageController@store']);
Route::get('LanguageController/edit/{id}', "LanguageController@edit");
Route::post('LanguageController/update/{id}', "LanguageController@update");
Route::get('LanguageController/chooser_language/{id}',"LanguageController@chooser_language" );
Route::get('/LanguageController/destroy/{id}/{lan}', "LanguageController@destroy");

/* roles and Permission */
Route::get('/roles', "RoleController@index");
Route::get('/RoleController/edit/{id}', "RoleController@edit");
Route::post('roles', ['as' => 'roles.store', 'uses' => 'RoleController@store']);
Route::post('RoleController/update/{id}','RoleController@update');
Route::get('/RoleController/destroy/{id}', "RoleController@destroy");

//Route::post('/roles', "RoleController@index");
Route::get('/permissions', "PermissionController@index");
Route::get('/PermissionController/edit/{id}', "PermissionController@edit");
Route::post('permissions', ['as' => 'permission.store','uses' => 'PermissionController@store']);
Route::post('PermissionController/update/{id}','PermissionController@update');
Route::post('permissions/save', ['as' => 'permission.save', 'uses' => 'PermissionController@saveRolePermissions']);
Route::get('/PermissionController/destroy/{id}', "PermissionController@destroy");

/* User Activity activity */ 
Route::get('/activity/', "ActivityController@index");
Route::get('/activity/user/{id}', "ActivityController@activity_user");

/* Setting */ 
Route::get('/settings/', "SettingController@index");
Route::post('/settings/', "SettingController@store");
Route::post('/SettingController/upload/{id}', "SettingController@upload");
Route::post('/SettingController/auth_registration', "SettingController@auth_registration");

Route::get('/SettingController/sidebar', "SettingController@sidebar");

/* Dashboard */ 
Route::get('/dashboard/', "DashboardController@index");


/* Message */ 
Route::get('/message/', "MessageController@index");
Route::get('/SendMessage/', "MessageController@sendmail");
Route::get('/sendDetails/{id}', "MessageController@sendDetails");
Route::get('/inboxDetails/{id}/{replayidid}', "MessageController@inboxDetails");
Route::post('MessageController/save/', "MessageController@store");
Route::post('MessageController/destroy/', "MessageController@destroy");



/* Authentication routes...*/
// Route::get('auth/login', 'Auth\AuthController@getLogin');
// Route::post('auth/login', 'Auth\AuthController@postLogin');
// Route::get('auth/logout', 'Auth\AuthController@getLogout');
Route::auth();
Route::resource('permission', 'PermissionsController');

/* Basic Elements */
/* besic controller*/
Route::get('/buttons', 'ElementsController@buttons');
Route::get('/dropdowns', 'ElementsController@dropdowns');
Route::get('/icons', 'ElementsController@icons');
Route::get('/ElementsController/brandIcons', 'ElementsController@brandIcons');
Route::get('/ElementsController/fontAwesome', 'ElementsController@fontAwesome');
Route::get('/ElementsController/strokeIcon', 'ElementsController@strokeIcon');
Route::get('/ElementsController/glyphicons', 'ElementsController@glyphicons');
Route::get('/ElementsController/ionicons', 'ElementsController@ionicons');
Route::get('/ElementsController/materialDesign', 'ElementsController@materialDesign');
Route::get('/ElementsController/mfglabs', 'ElementsController@mfglabs');
Route::get('/ElementsController/octicons', 'ElementsController@octicons');
Route::get('/ElementsController/openIconic', 'ElementsController@openIconic');
Route::get('/ElementsController/themify', 'ElementsController@themify');
Route::get('/ElementsController/weatherIcons', 'ElementsController@weatherIcons');
Route::get('/ElementsController/webIcons', 'ElementsController@webIcons');
Route::get('/tooltip', 'ElementsController@tooltip');
Route::get('/modals', 'ElementsController@modals');
Route::get('/tabsAccordions', 'ElementsController@tabsAccordions');
Route::get('/imagesDes', 'ElementsController@imagesDes');
Route::get('/badgesLabels', 'ElementsController@badgesLabels');
Route::get('/progressBars', 'ElementsController@progressBars');
Route::get('/carousel', 'ElementsController@carousel');
Route::get('/carousel', 'ElementsController@carousel');
Route::get('/typography', 'ElementsController@typography');
Route::get('/colors', 'ElementsController@colors');
Route::get('/animation', 'ElementsController@animation');
Route::get('/lightbox', 'ElementsController@lightbox');
Route::get('/scrollable', 'ElementsController@scrollable');
Route::get('/rating', 'ElementsController@rating');
Route::get('/toastr', 'ElementsController@toastr');
Route::get('/sortableNestable', 'ElementsController@sortableNestable');
Route::get('/bootboxSweetalert', 'ElementsController@bootboxSweetalert');
Route::get('/alerts', 'ElementsController@alerts');
Route::get('/ribbon', 'ElementsController@ribbon');
Route::get('/pricingTables', 'ElementsController@pricingTables');
Route::get('/overlay', 'ElementsController@overlay');
Route::get('/cover', 'ElementsController@cover');
Route::get('/timeline', 'ElementsController@timeline');
Route::get('/step', 'ElementsController@step');
Route::get('/chat', 'ElementsController@chat');
Route::get('/social', 'ElementsController@social');
Route::get('/general', 'ElementsController@general');
Route::get('/material', 'ElementsController@material');
Route::get('/layouts', 'ElementsController@layouts');
Route::get('/wizard', 'ElementsController@wizard');
Route::get('/validation', 'ElementsController@validation');
Route::get('/masks', 'ElementsController@masks');
Route::get('/imageCropping', 'ElementsController@imageCropping');
Route::get('/fileUploads', 'ElementsController@fileUploads');
Route::get('/basicTables', 'ElementsController@basicTables');
Route::get('/responsiveTable', 'ElementsController@responsiveTable');
Route::get('/editableTable', 'ElementsController@editableTable');
Route::get('/jsgrid', 'ElementsController@jsgrid');
Route::get('/faq', 'ElementsController@faq');
Route::get('/gallery', 'ElementsController@gallery');
Route::get('/searchResult', 'ElementsController@searchResult');
Route::get('/invoice', 'ElementsController@invoice');
Route::get('/profiledemo', 'ElementsController@profiledemo');
Route::get('/error400', 'ElementsController@error400');
Route::get('/error500', 'ElementsController@error500');
Route::get('/logout', 'DashboardController@index');


//Trash categories
Route::get("dashboard/product/categories/trash", "Dashboard\TrashController@categories_products_trash")->name("categories_products_trash");
//Restore Categories
// Route::get("dashboard/product/categories/restore", "Dashboard\CategoryController@categories_products_restore")->name("categories_products_restore");



//Product Attributes
Route::match(["get","post"],"dashboard/products/attributes/{id}", "Dashboard\ProductsController@product_attributes")->name("product-attributes");
//Add Alternate images Product
// Route::match(["get","post"],"dashboard/products/add-images/{id}", "Dashboard\ProductsController@add_image_product")->name("add_image_product");

//Borrado permanente
Route::get("dashboard/products/trash/destroy/{id}", 
				"Dashboard\TrashController@destroy_product_products_trash");

//Route Group
Route::group(["middleware" => ["auth"]], function (){
	
	//Categories Products
	Route::resource("dashboard/product/categories", "Dashboard\CategoryController");

	//Products
	Route::resource("dashboard/products", "Dashboard\ProductsController");
		//Add Images: Añade imagenes opcionales al producto desde la vista edición del producto
		// Route::get("dashboard/products/add-images/{id}",											"Dashboard\ProductsController@add_image_product")->name("add_optional_images");
				
		//Delete Image: Borrar imagen del producto, en la vista edición del producto
		Route::get("dashboard/products/delete-image/{id}",											"Dashboard\TrashController@delete_image_product" )
				->name("delete-image-product");

		//softDeletes Product
		Route::get("product/product-trash/{id}", "Dashboard\ProductsController@softDelete");
		Route::match(["get", "post"],'dashboard/product/trash', "Dashboard\TrashController@product_softDeletes");

		//Restaurar productos
		Route::get("product/product-restore/{id}", "Dashboard\ProductsController@product_restore");

		//Borrado Permanente de producto
		Route::match(["get","post"], "dashboar/product/product-deleted/{id}", "Dashboard\TrashController@product_hard_delete" );

		//Borrar attributos del producto
		Route::get("dashboard/products/attributes/delete/{id}", "Dashboard\ProductsController@product_attributes_delete")->name("product_attributes_delete");
		
		//Editar atributos del producto 
		Route::match(["get", "post"],"dashboard/products/attributes/edit/{id}", "Dashboard\ProductsController@product_attributes_edit");


	//Diseño del FrontEnd Desde el Dashboard

		Route::resource('dashboard/config/design/banners', "Dashboard\BannersController");
	//softDeletes Banners
		Route::get('dashboard/config/design/banners/trashed/{id}', 
			"Dashboard\BannersController@softDelete");
	//banners en papelera
	Route::get('dashboard/config/d-sign/banners/trash', "Dashboard\BannersController@banner_trashes");
	//Restaurar banner
	Route::get("dashboard/config/d-sign/banners/restore/{id}", "Dashboard\BannersController@banner_restore");
	//Borrado de banners

resources/views/dashboard/configuracion/design/partials/form_create_banner.blade.php
@section("styles")
   <link rel="stylesheet" href="{{URL::to('/')}}/global/vendor/blueimp-file-upload/jquery.fileupload.css">
  <link rel="stylesheet" href="{{URL::to('/')}}/global/vendor/dropify/dropify.css">
@endsection

<div class="row">

  <div class="col-xs-12  col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <div class="form-group">
      {{ Form::label("name", "Nombre del Banner") }}
      {{ Form::text("title",null, ["class" => "form-control", "id" => "title"])}} 
    </div>

    <div class="form-group">
      {{ Form::label("slug", "Slug") }}
      {{ Form::text("url",null, ["class" => "form-control", "id" => "slug"])}} 
    </div>
  </div>

   <div class="col-xs-12  col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <input type="file" name="image">

    {{--  --}}
    
  </div>


</div>
<div class="row">
  <div class="col-md-9">
    

   <div class="form-group">
      {{ Form::label("description", "Descripción") }}
      {{ Form::textarea("description",null, ["class" => "form-control", "id" => "description"])}} 
    </div>


    <div class="form-group">
      <div class="checkbox-custom checkbox-primary">
        <input type="hidden" id="status" name="status" value="PUBLISHED" />
       
      </div>
    </div>

  </div>
  
</div>

<div class="row">
    <div class="form-group">
      {{ Form::submit("Crear", ["class" => "btn btn-success btn-sm"]) }}

       <button type="reset" class="btn btn-danger  btn-sm">
        Borrar
      </button>

      <a href="{{ url("dashboard/config/design/banners") }}">
        <button type="button" class="btn btn-warning btn-sm">
          Volver
        </button>
      </a>
      
    </div>
</div>


@section("scripts")
  <script src="{{ asset("vendor/jquerystringToSlug/jquery-stringToSlug.min.js") }} "></script>
  <script src="{{ asset("vendor/ckeditor/ckeditor.js") }} "></script>
  
  
  <script>
    $(document).ready(function () {
      $("#title, #slug").stringToSlug({
        callback: function (text) {
          $("#slug").val(text);
        }
      });
    });

    /*CK EDITOR*/
    CKEDITOR.config.height=400;
    CKEDITOR.config.width="auto";

    CKEDITOR.replace("description");

    $(document).ready(function() {
      $("#form-products").validate();
    });
  </script>
@endsection

resources/views/dashboard/configuracion/design/partials/form_edit_banner.blade.php
@section("styles")
   <link rel="stylesheet" href="{{URL::to('/')}}/global/vendor/blueimp-file-upload/jquery.fileupload.css">
  <link rel="stylesheet" href="{{URL::to('/')}}/global/vendor/dropify/dropify.css">
@endsection

<div class="row">

  <div class="col-xs-12  col-sm-12 col-md-6 col-lg-6 col-xl-6">
    <div class="form-group">
      {{ Form::label("name", "Nombre del Banner") }}
      {{ Form::text("title",null, ["class" => "form-control", "id" => "title"])}} 
    </div>

    <div class="form-group">
      {{ Form::label("slug", "Slug") }}
      {{ Form::text("url",null, ["class" => "form-control", "id" => "slug"])}} 
    </div>

  </div>

   <div class="col-xs-12  col-sm-12 col-md-6 col-lg-6 col-xl-6">

    <input type="file" name="image">

    @if($banner->image)
     <figcaption><small><strong>Nota: La imagen debe tener una dimensión de 545 x 630</strong></small></figcaption>
      <img src="{{ asset("images/frontend/banners/$banner->image") }}" width="100px" title="Imagen de 545 x 630">

    @else
      <i class="fa fa-img"></i>
    @endif
    {{--  --}}
    
  </div>


</div>
<div class="row">
  <div class="col-md-9">
    

   <div class="form-group">
      {{ Form::label("description", "Descripción") }}
      {{ Form::textarea("description",null, ["class" => "form-control", "id" => "description"])}} 
    </div>

   <div class="form-group">
     <div class="checkbox-custom checkbox-primary">
        <input type="checkbox" id="status" name="status" @if($banner->status==1) checked @endif value="1"  />
        <label for="inputChecked">Activo</label>
      </div> 
    </div>

    <div class="form-group">
      <div class="checkbox-custom checkbox-primary">
        <input type="hidden" id="status" name="status" value="PUBLISHED" />
       
      </div>
    </div>

  </div>
  
</div>

<div class="row">
    <div class="form-group">
      {{ Form::submit("Actualizar", ["class" => "btn btn-success btn-sm"]) }}

      <a href="{{ url("dashboard/config/design/banners") }}">
        <button type="button" class="btn btn-warning btn-sm">
          Volver
        </button>
      </a>
      
    </div>
</div>


@section("scripts")
  <script src="{{ asset("vendor/jquerystringToSlug/jquery-stringToSlug.min.js") }} "></script>
  <script src="{{ asset("vendor/ckeditor/ckeditor.js") }} "></script>
  
  
  <script>
    $(document).ready(function () {
      $("#title, #slug").stringToSlug({
        callback: function (text) {
          $("#slug").val(text);
        }
      });
    });

    /*CK EDITOR*/
    CKEDITOR.config.height=400;
    CKEDITOR.config.width="auto";

    CKEDITOR.replace("description");

    $(document).ready(function() {
      $("#form-products").validate();
    });
  </script>
@endsection

resources/views/dashboard/configuracion/design/partials/modal_delete.blade.php
                <div class="modal fade modal-3d-flip-vertical" id="modal-delete-{{ $banner_t->id }}" aria-hidden="true"
                  aria-labelledby="exampleModalTitle" role="dialog" tabindex="-1">
                 
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header bg-danger">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                          <h4 class="modal-title" style="color: white!important;">Eliminar del sistema</h4>
                        </div>
                        <div class="modal-body">
                          <p>¿Estas seguro de eliminar el banner {{ $banner_t->title }} permanentemente? <br>
                            <small class="text-warning">Advertencia: Si continuas ya no podrás recuperar el banner</small>
                          </p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-outline btn-default margin-0" data-dismiss="modal">Cancelar</button>
                         <a href="{{ url("dashboard/config/d-sign/banners/delete", $banner_t->id) }}">
                            <button type="submit" class="btn btn-outline btn-danger">Continuar</button>
                         </a>
                        </div>
                      </div>
                    </div>
                   
                  </div>

resources/views/dashboard/configuracion/design/partials/modal_details.blade.php
 <div class="modal fade modal-3d-slit" id="modal-view-{{ $banner->id }}" aria-hidden="true"
                  aria-labelledby="exampleModalTitle" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Detalles de {{$banner->title}}</h4>
           <ul class="nav nav-tabs nav-tabs-line" data-plugin="nav-tabs" role="tablist">
              <li class="active" role="presentation"><a data-toggle="tab" href="#exampleLine1" aria-controls="exampleLine1" role="tab">Detalles</a></li>
              <li role="presentation"><a data-toggle="tab" href="#exampleLine2" aria-controls="exampleLine2" role="tab">Desripción</a></li>
              <li role="presentation"><a data-toggle="tab" href="#exampleLine3" aria-controls="exampleLine3" role="tab">CSS</a></li>
              <li role="presentation"><a data-toggle="tab" href="#exampleLine4" aria-controls="exampleLine4" role="tab">JavaScript</a></li>
            </ul>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-sm-12 col-md-4 col-lg-4">
                @if($banner->image)
                  <img src="{{ asset("images/frontend/banners/$banner->image") }}" width="250px">
                  @else
                    <img src="{{URL::to('/')}}/global/photos/placeholder.png" width="250px">
                @endif
            </div>
            <div class="col-sm-12 col-md-8 col-lg-8">
              <div class="tab-content">
                  <div class="tab-pane active" id="exampleLine1" role="tabpanel">
                    Dettale de banner
                    {{--  <p>Precio: {{ $banner->price }}</p>  --}}   
                  </div>
                  <div class="tab-pane" id="exampleLine2" role="tabpanel">
                    {!! $banner->title !!}    
                  </div>
                  <div class="tab-pane" id="exampleLine3" role="tabpanel">
                  Cernimus nutu. Maioribus solet. Iustitiam conciliant reliquisti instituendarum
                                  
                  </div>
                  <div class="tab-pane" id="exampleLine4" role="tabpanel">
                    Nec iste vellem, accusamus inesse exhorrescere tertium dominationis licebit perpetiuntur,                
                  </div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline btn-warning btn-xs" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>

resources/views/dashboard/configuracion/design/partials/modal_trash.blade.php
                <div class="modal fade modal-3d-flip-vertical" id="modal-delete-{{ $banner->id }}" aria-hidden="true"
                  aria-labelledby="exampleModalTitle" role="dialog" tabindex="-1">
                  {{--  {{{ Form::Open(array("action" => array("Dashboard\bannersController@destroy", $banner->id), "method" => "DELETE")) }}} --}}
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header bg-danger">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                          <h4 class="modal-title" style="color: white!important;">Enviar a la papelera</h4>
                        </div>
                        <div class="modal-body">
                          <p>¿Estas seguro de enviar el banner {{ $banner->title }} a la papelera? <br>
                            <small class="text-success">Tienes la opción de restaurarlo más tarde</small>
                          </p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-outline btn-default margin-0" data-dismiss="modal">Cancelar</button>
                         <a href="{{ url("dashboard/config/design/banners/trashed", $banner->id) }}">
                            <button type="submit" class="btn btn-outline btn-danger">Continuar</button>
                         </a>
                        </div>
                      </div>
                    </div>
                    {{--  {{ Form::close() }} --}}
                  </div>

resources/views/dashboard/configuracion/design/partials/search.blade.php
 <div class="form-group">
   <div class="input-search">
   	<form role="search" method="get" action="{{ route("banners.index") }}">
	     <button type="submit" class="input-search-btn"><i class="icon wb-search" aria-hidden="true"></i></button>
	     <input type="text" class="form-control" name="searchText" placeholder="Buscar productos por nombre o código..." value="{{$searchText}}">
	   </div>
	</form>
 </div>